name: 'Edge Addon Action'
description: 'Upload your addon to Edge Add-ons'
author: 'Malachi Soord'
inputs:
  product_id:
    required: true
    description: 'The extension product ID'
  client_id:
    required: true
    description: 'The client ID'
  api_key:
    required: true
    description: 'The API key'
  zip:
    required: true
    description: 'Path to a .zip of your addon'
  notes:
    required: false
    description: 'The notes to include when uploading a new release'
    default: 'New version'
  debug:
    required: false
    description: 'Whether to print debug information'
    default: 'false'
  retry_count:
    required: false
    description: 'Number of times to retry the upload on failure'
    default: '3'
  sleep_seconds:
    required: false
    description: 'Number of seconds to wait between retries'
    default: '5'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.product_id }}
    - ${{ inputs.client_id }}
    - ${{ inputs.api_key }}
    - ${{ inputs.zip }}
    - ${{ inputs.notes }}
    - ${{ inputs.debug }}
    - ${{ inputs.retry_count }}
    - ${{ inputs.sleep_seconds }}
branding:
  icon: 'book'
  color: 'blue'
