name: CI

on:
  push:
    branches: [master]
  pull_request: ~

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install pip dependencies
      run: pip install -r requirements-dev.txt
    - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install pip dependencies
      run: pip install -r requirements-dev.txt
    - name: Run tests
      run: python -m pytest -v
